const stateCities = {
  MG: [
    "ABADIA DOS DOURADOS",
    "ABAETÉ",
    "ABRE CAMPO",
    "ACAIACA",
    "AÇUCENA",
    "ÁGUA BOA",
    "ÁGUA COMPRIDA",
    "AGUANIL",
    "ÁGUAS FORMOSAS",
    "ÁGUAS VERMELHAS",
    "AIMORÉS",
    "AIURUOCA",
    "ALAGOA",
    "ALBERTINA",
    "ALÉM PARAÍBA",
    "ALFENAS",
    "ALFREDO VASCONCELOS",
    "ALMENARA",
    "ALPERCATA",
    "ALPINÓPOLIS",
    "ALTEROSA",
    "ALTO CAPARAÓ",
    "ALTO JEQUITIBÁ",
    "ALTO RIO DOCE",
    "ALVARENGA",
    "ALVINÓPOLIS",
    "ALVORADA DE MINAS",
    "AMPARO DO SERRA",
    "ANDRADAS",
    "ANDRELÂNDIA",
    "ANGELÂNDIA",
    "ANTÔNIO CARLOS",
    "ANTÔNIO DIAS",
    "ANTÔNIO PRADO DE MINAS",
    "ARAÇAÍ",
    "ARACITABA",
    "ARAÇUAÍ",
    "ARAGUARI",
    "ARANTINA",
    "ARAPONGA",
    "ARAPORÃ",
    "ARAPUÁ",
    "ARAÚJOS",
    "ARAXÁ",
    "ARCEBURGO",
    "ARCOS",
    "AREADO",
    "ARGIRITA",
    "ARICANDUVA",
    "ARINOS",
    "ASTOLFO DUTRA",
    "ATALÉIA",
    "AUGUSTO DE LIMA",
    "BAEPENDI",
    "BALDIM",
    "BAMBUÍ",
    "BANDEIRA",
    "BANDEIRA DO SUL",
    "BARÃO DE COCAIS",
    "BARÃO DE MONTE ALTO",
    "BARBACENA",
    "BARRA LONGA",
    "BARROSO",
    "BELA VISTA DE MINAS",
    "BELMIRO BRAGA",
    "BELO HORIZONTE",
    "BELO ORIENTE",
    "BELO VALE",
    "BERILO",
    "BERIZAL",
    "BERTÓPOLIS",
    "BETIM",
    "BIAS FORTES",
    "BICAS",
    "BIQUINHAS",
    "BOA ESPERANÇA",
    "BOCAINA DE MINAS",
    "BOCAIÚVA",
    "BOM DESPACHO",
    "BOM JARDIM DE MINAS",
    "BOM JESUS DA PENHA",
    "BOM JESUS DO AMPARO",
    "BOM JESUS DO GALHO",
    "BOM REPOUSO",
    "BOM SUCESSO",
    "BONFIM",
    "BONFINÓPOLIS DE MINAS",
    "BONITO DE MINAS",
    "BORDA DA MATA",
    "BOTELHOS",
    "BOTUMIRIM",
    "BRÁS PIRES",
    "BRASILÂNDIA DE MINAS",
    "BRASÍLIA DE MINAS",
    "BRASÓPOLIS",
    "BRAÚNAS",
    "BRUMADINHO",
    "BUENO BRANDÃO",
    "BUENÓPOLIS",
    "BUGRE",
    "BURITIS",
    "BURITIZEIRO",
    "CABECEIRA GRANDE",
    "CABO VERDE",
    "CACHOEIRA DA PRATA",
    "CACHOEIRA DE MINAS",
    "CACHOEIRA DE PAJEÚ",
    "CACHOEIRA DOURADA",
    "CAETANÓPOLIS",
    "CAETÉ",
    "CAIANA",
    "CAJURI",
    "CALDAS",
    "CAMACHO",
    "CAMANDUCAIA",
    "CAMBUÍ",
    "CAMBUQUIRA",
    "CAMPANÁRIO",
    "CAMPANHA",
    "CAMPESTRE",
    "CAMPINA VERDE",
    "CAMPO AZUL",
    "CAMPO BELO",
    "CAMPO DO MEIO",
    "CAMPO FLORIDO",
    "CAMPOS ALTOS",
    "CAMPOS GERAIS",
    "CANA VERDE",
    "CANAÃ",
    "CANÁPOLIS",
    "CANDEIAS",
    "CANTAGALO",
    "CAPARAÓ",
    "CAPELA NOVA",
    "CAPELINHA",
    "CAPETINGA",
    "CAPIM BRANCO",
    "CAPINÓPOLIS",
    "CAPITÃO ANDRADE",
    "CAPITÃO ENÉAS",
    "CAPITÓLIO",
    "CAPUTIRA",
    "CARAÍ",
    "CARANAÍBA",
    "CARANDAÍ",
    "CARANGOLA",
    "CARATINGA",
    "CARBONITA",
    "CAREAÇU",
    "CARLOS CHAGAS",
    "CARMÉSIA",
    "CARMO DA CACHOEIRA",
    "CARMO DA MATA",
    "CARMO DE MINAS",
    "CARMO DO CAJURU",
    "CARMO DO PARANAÍBA",
    "CARMO DO RIO CLARO",
    "CARMÓPOLIS DE MINAS",
    "CARNEIRINHO",
    "CARRANCAS",
    "CARVALHÓPOLIS",
    "CARVALHOS",
    "CASA GRANDE",
    "CASCALHO RICO",
    "CÁSSIA",
    "CATAGUASES",
    "CATAS ALTAS",
    "CATAS ALTAS DA NORUEGA",
    "CATUJI",
    "CATUTI",
    "CAXAMBU",
    "CEDRO DO ABAETÉ",
    "CENTRAL DE MINAS",
    "CENTRALINA",
    "CHÁCARA",
    "CHALÉ",
    "CHAPADA DO NORTE",
    "CHAPADA GAÚCHA",
    "CHIADOR",
    "CIPOTÂNEA",
    "CLARAVAL",
    "CLARO DOS POÇÕES",
    "CLÁUDIO",
    "COIMBRA",
    "COLUNA",
    "COMENDADOR GOMES",
    "COMERCINHO",
    "CONCEIÇÃO DA APARECIDA",
    "CONCEIÇÃO DA BARRA DE MINAS",
    "CONCEIÇÃO DAS ALAGOAS",
    "CONCEIÇÃO DAS PEDRAS",
    "CONCEIÇÃO DE IPANEMA",
    "CONCEIÇÃO DO MATO DENTRO",
    "CONCEIÇÃO DO PARÁ",
    "CONCEIÇÃO DO RIO VERDE",
    "CONCEIÇÃO DOS OUROS",
    "CÔNEGO MARINHO",
    "CONFINS",
    "CONGONHAL",
    "CONGONHAS",
    "CONGONHAS DO NORTE",
    "CONQUISTA",
    "CONSELHEIRO LAFAIETE",
    "CONSELHEIRO PENA",
    "CONSOLAÇÃO",
    "CONTAGEM",
    "COQUEIRAL",
    "CORAÇÃO DE JESUS",
    "CORDISBURGO",
    "CORDISLÂNDIA",
    "CORINTO",
    "COROACI",
    "COROMANDEL",
    "CORONEL FABRICIANO",
    "CORONEL MURTA",
    "CORONEL PACHECO",
    "CORONEL XAVIER CHAVES",
    "CÓRREGO DANTA",
    "CÓRREGO DO BOM JESUS",
    "CÓRREGO FUNDO",
    "CÓRREGO NOVO",
    "COUTO DE MAGALHÃES DE MINAS",
    "CRISÓLITA",
    "CRISTAIS",
    "CRISTÁLIA",
    "CRISTIANO OTONI",
    "CRISTINA",
    "CRUCILÂNDIA",
    "CRUZEIRO DA FORTALEZA",
    "CRUZÍLIA",
    "CUPARAQUE",
    "CURRAL DE DENTRO",
    "CURVELO",
    "DATAS",
    "DELFIM MOREIRA",
    "DELFINÓPOLIS",
    "DELTA",
    "DESCOBERTO",
    "DESTERRO DE ENTRE RIOS",
    "DESTERRO DO MELO",
    "DIAMANTINA",
    "DIOGO DE VASCONCELOS",
    "DIONÍSIO",
    "DIVINÉSIA",
    "DIVINO",
    "DIVINO DAS LARANJEIRAS",
    "DIVINOLÂNDIA DE MINAS",
    "DIVINÓPOLIS",
    "DIVISA ALEGRE",
    "DIVISA NOVA",
    "DIVISÓPOLIS",
    "DOM BOSCO",
    "DOM CAVATI",
    "DOM JOAQUIM",
    "DOM SILVÉRIO",
    "DOM VIÇOSO",
    "DONA EUZÉBIA",
    "DORES DE CAMPOS",
    "DORES DE GUANHÃES",
    "DORES DO INDAIÁ",
    "DORES DO TURVO",
    "DORESÓPOLIS",
    "DOURADOQUARA",
    "DURANDÉ",
    "ELÓI MENDES",
    "ENGENHEIRO CALDAS",
    "ENGENHEIRO NAVARRO",
    "ENTRE FOLHAS",
    "ENTRE RIOS DE MINAS",
    "ERVÁLIA",
    "ESMERALDAS",
    "ESPERA FELIZ",
    "ESPINOSA",
    "ESPÍRITO SANTO DO DOURADO",
    "ESTIVA",
    "ESTRELA DALVA",
    "ESTRELA DO INDAIÁ",
    "ESTRELA DO SUL",
    "EUGENÓPOLIS",
    "EWBANK DA CÂMARA",
    "EXTREMA",
    "FAMA",
    "FARIA LEMOS",
    "FELÍCIO DOS SANTOS",
    "FELISBURGO",
    "FELIXLÂNDIA",
    "FERNANDES TOURINHO",
    "FERROS",
    "FERVEDOURO",
    "FLORESTAL",
    "FORMIGA",
    "FORMOSO",
    "FORTALEZA DE MINAS",
    "FORTUNA DE MINAS",
    "FRANCISCO BADARÓ",
    "FRANCISCO DUMONT",
    "FRANCISCO SÁ",
    "FRANCISCÓPOLIS",
    "FREI GASPAR",
    "FREI INOCÊNCIO",
    "FREI LAGONEGRO",
    "FRONTEIRA",
    "FRONTEIRA DOS VALES",
    "FRUTA DE LEITE",
    "FRUTAL",
    "FUNILÂNDIA",
    "GALILÉIA",
    "GAMELEIRAS",
    "GLAUCILÂNDIA",
    "GOIABEIRA",
    "GOIANÁ",
    "GONÇALVES",
    "GONZAGA",
    "GOUVEIA",
    "GOVERNADOR VALADARES",
    "GRÃO MOGOL",
    "GRUPIARA",
    "GUANHÃES",
    "GUAPÉ",
    "GUARACIABA",
    "GUARACIAMA",
    "GUARANÉSIA",
    "GUARANI",
    "GUARARÁ",
    "GUARDA-MOR",
    "GUAXUPÉ",
    "GUIDOVAL",
    "GUIMARÂNIA",
    "GUIRICEMA",
    "GURINHATÃ",
    "HELIODORA",
    "IAPU",
    "IBERTIOGA",
    "IBIÁ",
    "IBIAÍ",
    "IBIRACATU",
    "IBIRACI",
    "IBIRITÉ",
    "IBITIÚRA DE MINAS",
    "IBITURUNA",
    "ICARAÍ DE MINAS",
    "IGARAPÉ",
    "IGARATINGA",
    "IGUATAMA",
    "IJACI",
    "ILICÍNEA",
    "IMBÉ DE MINAS",
    "INCONFIDENTES",
    "INDAIABIRA",
    "INDIANÓPOLIS",
    "INGAÍ",
    "INHAPIM",
    "INHAÚMA",
    "INIMUTABA",
    "IPABA",
    "IPANEMA",
    "IPATINGA",
    "IPIAÇU",
    "IPUIÚNA",
    "IRAÍ DE MINAS",
    "ITABIRA",
    "ITABIRINHA DE MANTENA",
    "ITABIRITO",
    "ITACAMBIRA",
    "ITACARAMBI",
    "ITAGUARA",
    "ITAIPÉ",
    "ITAJUBÁ",
    "ITAMARANDIBA",
    "ITAMARATI DE MINAS",
    "ITAMBACURI",
    "ITAMBÉ DO MATO DENTRO",
    "ITAMOGI",
    "ITAMONTE",
    "ITANHANDU",
    "ITANHOMI",
    "ITAOBIM",
    "ITAPAGIPE",
    "ITAPECERICA",
    "ITAPEVA",
    "ITATIAIUÇU",
    "ITAÚ DE MINAS",
    "ITAÚNA",
    "ITAVERAVA",
    "ITINGA",
    "ITUETA",
    "ITUIUTABA",
    "ITUMIRIM",
    "ITURAMA",
    "ITUTINGA",
    "JABOTICATUBAS",
    "JACINTO",
    "JACUÍ",
    "JACUTINGA",
    "JAGUARAÇU",
    "JAÍBA",
    "JAMPRUCA",
    "JANAÚBA",
    "JANUÁRIA",
    "JAPARAÍBA",
    "JAPONVAR",
    "JECEABA",
    "JENIPAPO DE MINAS",
    "JEQUERI",
    "JEQUITAÍ",
    "JEQUITIBÁ",
    "JEQUITINHONHA",
    "JESUÂNIA",
    "JOAÍMA",
    "JOANÉSIA",
    "JOÃO MONLEVADE",
    "JOÃO PINHEIRO",
    "JOAQUIM FELÍCIO",
    "JORDÂNIA",
    "JOSÉ GONÇALVES DE MINAS",
    "JOSÉ RAYDAN",
    "JOSENÓPOLIS",
    "JUATUBA",
    "JUIZ DE FORA",
    "JURAMENTO",
    "JURUAIA",
    "JUVENÍLIA",
    "LADAINHA",
    "LAGAMAR",
    "LAGOA DA PRATA",
    "LAGOA DOS PATOS",
    "LAGOA DOURADA",
    "LAGOA FORMOSA",
    "LAGOA GRANDE",
    "LAGOA SANTA",
    "LAJINHA",
    "LAMBARI",
    "LAMIM",
    "LARANJAL",
    "LASSANCE",
    "LAVRAS",
    "LEANDRO FERREIRA",
    "LEME DO PRADO",
    "LEOPOLDINA",
    "LIBERDADE",
    "LIMA DUARTE",
    "LIMEIRA DO OESTE",
    "LONTRA",
    "LUISBURGO",
    "LUISLÂNDIA",
    "LUMINÁRIAS",
    "LUZ",
    "MACHACALIS",
    "MACHADO",
    "MADRE DE DEUS DE MINAS",
    "MALACACHETA",
    "MAMONAS",
    "MANGA",
    "MANHUAÇU",
    "MANHUMIRIM",
    "MANTENA",
    "MAR DE ESPANHA",
    "MARAVILHAS",
    "MARIA DA FÉ",
    "MARIANA",
    "MARILAC",
    "MÁRIO CAMPOS",
    "MARIPÁ DE MINAS",
    "MARLIÉRIA",
    "MARMELÓPOLIS",
    "MARTINHO CAMPOS",
    "MARTINS SOARES",
    "MATA VERDE",
    "MATERLÂNDIA",
    "MATEUS LEME",
    "MATHIAS LOBATO",
    "MATIAS BARBOSA",
    "MATIAS CARDOSO",
    "MATIPÓ",
    "MATO VERDE",
    "MATOZINHOS",
    "MATUTINA",
    "MEDEIROS",
    "MEDINA",
    "MENDES PIMENTEL",
    "MERCÊS",
    "MESQUITA",
    "MINAS NOVAS",
    "MINDURI",
    "MIRABELA",
    "MIRADOURO",
    "MIRAÍ",
    "MIRAVÂNIA",
    "MOEDA",
    "MOEMA",
    "MONJOLOS",
    "MONSENHOR PAULO",
    "MONTALVÂNIA",
    "MONTE ALEGRE DE MINAS",
    "MONTE AZUL",
    "MONTE BELO",
    "MONTE CARMELO",
    "MONTE FORMOSO",
    "MONTE SANTO DE MINAS",
    "MONTE SIÃO",
    "MONTES CLAROS",
    "MONTEZUMA",
    "MORADA NOVA DE MINAS",
    "MORRO DA GARÇA",
    "MORRO DO PILAR",
    "MUNHOZ",
    "MURIAÉ",
    "MUTUM",
    "MUZAMBINHO",
    "NACIP RAYDAN",
    "NANUQUE",
    "NAQUE",
    "NATALÂNDIA",
    "NATÉRCIA",
    "NAZARENO",
    "NEPOMUCENO",
    "NINHEIRA",
    "NOVA BELÉM",
    "NOVA ERA",
    "NOVA LIMA",
    "NOVA MÓDICA",
    "NOVA PONTE",
    "NOVA PORTEIRINHA",
    "NOVA RESENDE",
    "NOVA SERRANA",
    "NOVA UNIÃO",
    "NOVO CRUZEIRO",
    "NOVO ORIENTE DE MINAS",
    "NOVORIZONTE",
    "OLARIA",
    "OLHOS-D'ÁGUA",
    "OLÍMPIO NORONHA",
    "OLIVEIRA",
    "OLIVEIRA FORTES",
    "ONÇA DE PITANGUI",
    "ORATÓRIOS",
    "ORIZÂNIA",
    "OURO BRANCO",
    "OURO FINO",
    "OURO PRETO",
    "OURO VERDE DE MINAS",
    "PADRE CARVALHO",
    "PADRE PARAÍSO",
    "PAI PEDRO",
    "PAINEIRAS",
    "PAINS",
    "PAIVA",
    "PALMA",
    "PALMÓPOLIS",
    "PAPAGAIOS",
    "PARÁ DE MINAS",
    "PARACATU",
    "PARAGUAÇU",
    "PARAISÓPOLIS",
    "PARAOPEBA",
    "PASSA QUATRO",
    "PASSA TEMPO",
    "PASSA-VINTE",
    "PASSABÉM",
    "PASSOS",
    "PATIS",
    "PATOS DE MINAS",
    "PATROCÍNIO",
    "PATROCÍNIO DO MURIAÉ",
    "PAULA CÂNDIDO",
    "PAULISTAS",
    "PAVÃO",
    "PEÇANHA",
    "PEDRA AZUL",
    "PEDRA BONITA",
    "PEDRA DO ANTA",
    "PEDRA DO INDAIÁ",
    "PEDRA DOURADA",
    "PEDRALVA",
    "PEDRAS DE MARIA DA CRUZ",
    "PEDRINÓPOLIS",
    "PEDRO LEOPOLDO",
    "PEDRO TEIXEIRA",
    "PEQUERI",
    "PEQUI",
    "PERDIGÃO",
    "PERDIZES",
    "PERDÕES",
    "PERIQUITO",
    "PESCADOR",
    "PIAU",
    "PIEDADE DE CARATINGA",
    "PIEDADE DE PONTE NOVA",
    "PIEDADE DO RIO GRANDE",
    "PIEDADE DOS GERAIS",
    "PIMENTA",
    "PINGO-D'ÁGUA",
    "PINTÓPOLIS",
    "PIRACEMA",
    "PIRAJUBA",
    "PIRANGA",
    "PIRANGUÇU",
    "PIRANGUINHO",
    "PIRAPETINGA",
    "PIRAPORA",
    "PIRAÚBA",
    "PITANGUI",
    "PIUMHI",
    "PLANURA",
    "POÇO FUNDO",
    "POÇOS DE CALDAS",
    "POCRANE",
    "POMPÉU",
    "PONTE NOVA",
    "PONTO CHIQUE",
    "PONTO DOS VOLANTES",
    "PORTEIRINHA",
    "PORTO FIRME",
    "POTÉ",
    "POUSO ALEGRE",
    "POUSO ALTO",
    "PRADOS",
    "PRATA",
    "PRATÁPOLIS",
    "PRATINHA",
    "PRESIDENTE BERNARDES",
    "PRESIDENTE JUSCELINO",
    "PRESIDENTE KUBITSCHEK",
    "PRESIDENTE OLEGÁRIO",
    "PRUDENTE DE MORAIS",
    "QUARTEL GERAL",
    "QUELUZITO",
    "RAPOSOS",
    "RAUL SOARES",
    "RECREIO",
    "REDUTO",
    "RESENDE COSTA",
    "RESPLENDOR",
    "RESSAQUINHA",
    "RIACHINHO",
    "RIACHO DOS MACHADOS",
    "RIBEIRÃO DAS NEVES",
    "RIBEIRÃO VERMELHO",
    "RIO ACIMA",
    "RIO CASCA",
    "RIO DO PRADO",
    "RIO DOCE",
    "RIO ESPERA",
    "RIO MANSO",
    "RIO NOVO",
    "RIO PARANAÍBA",
    "RIO PARDO DE MINAS",
    "RIO PIRACICABA",
    "RIO POMBA",
    "RIO PRETO",
    "RIO VERMELHO",
    "RITÁPOLIS",
    "ROCHEDO DE MINAS",
    "RODEIRO",
    "ROMARIA",
    "ROSÁRIO DA LIMEIRA",
    "RUBELITA",
    "RUBIM",
    "SABARÁ",
    "SABINÓPOLIS",
    "SACRAMENTO",
    "SALINAS",
    "SALTO DA DIVISA",
    "SANTA BÁRBARA",
    "SANTA BÁRBARA DO LESTE",
    "SANTA BÁRBARA DO MONTE VERDE",
    "SANTA BÁRBARA DO TUGÚRIO",
    "SANTA CRUZ DE MINAS",
    "SANTA CRUZ DE SALINAS",
    "SANTA CRUZ DO ESCALVADO",
    "SANTA EFIGÊNIA DE MINAS",
    "SANTA FÉ DE MINAS",
    "SANTA HELENA DE MINAS",
    "SANTA JULIANA",
    "SANTA LUZIA",
    "SANTA MARGARIDA",
    "SANTA MARIA DE ITABIRA",
    "SANTA MARIA DO SALTO",
    "SANTA MARIA DO SUAÇUÍ",
    "SANTA RITA DE CALDAS",
    "SANTA RITA DE IBITIPOCA",
    "SANTA RITA DE JACUTINGA",
    "SANTA RITA DE MINAS",
    "SANTA RITA DO ITUETO",
    "SANTA RITA DO SAPUCAÍ",
    "SANTA ROSA DA SERRA",
    "SANTA VITÓRIA",
    "SANTANA DA VARGEM",
    "SANTANA DE CATAGUASES",
    "SANTANA DE PIRAPAMA",
    "SANTANA DO DESERTO",
    "SANTANA DO GARAMBÉU",
    "SANTANA DO JACARÉ",
    "SANTANA DO MANHUAÇU",
    "SANTANA DO PARAÍSO",
    "SANTANA DO RIACHO",
    "SANTANA DOS MONTES",
    "SANTO ANTÔNIO DO AMPARO",
    "SANTO ANTÔNIO DO AVENTUREIRO",
    "SANTO ANTÔNIO DO GRAMA",
    "SANTO ANTÔNIO DO ITAMBÉ",
    "SANTO ANTÔNIO DO JACINTO",
    "SANTO ANTÔNIO DO MONTE",
    "SANTO ANTÔNIO DO RETIRO",
    "SANTO ANTÔNIO DO RIO ABAIXO",
    "SANTO HIPÓLITO",
    "SANTOS DUMONT",
    "SÃO BENTO ABADE",
    "SÃO BRÁS DO SUAÇUÍ",
    "SÃO DOMINGOS DAS DORES",
    "SÃO DOMINGOS DO PRATA",
    "SÃO FÉLIX DE MINAS",
    "SÃO FRANCISCO",
    "SÃO FRANCISCO DE PAULA",
    "SÃO FRANCISCO DE SALES",
    "SÃO FRANCISCO DO GLÓRIA",
    "SÃO GERALDO",
    "SÃO GERALDO DA PIEDADE",
    "SÃO GERALDO DO BAIXIO",
    "SÃO GONÇALO DO ABAETÉ",
    "SÃO GONÇALO DO PARÁ",
    "SÃO GONÇALO DO RIO ABAIXO",
    "SÃO GONÇALO DO RIO PRETO",
    "SÃO GONÇALO DO SAPUCAÍ",
    "SÃO GOTARDO",
    "SÃO JOÃO BATISTA DO GLÓRIA",
    "SÃO JOÃO DA LAGOA",
    "SÃO JOÃO DA MATA",
    "SÃO JOÃO DA PONTE",
    "SÃO JOÃO DAS MISSÕES",
    "SÃO JOÃO DEL REI",
    "SÃO JOÃO DO MANHUAÇU",
    "SÃO JOÃO DO MANTENINHA",
    "SÃO JOÃO DO ORIENTE",
    "SÃO JOÃO DO PACUÍ",
    "SÃO JOÃO DO PARAÍSO",
    "SÃO JOÃO EVANGELISTA",
    "SÃO JOÃO NEPOMUCENO",
    "SÃO JOAQUIM DE BICAS",
    "SÃO JOSÉ DA BARRA",
    "SÃO JOSÉ DA LAPA",
    "SÃO JOSÉ DA SAFIRA",
    "SÃO JOSÉ DA VARGINHA",
    "SÃO JOSÉ DO ALEGRE",
    "SÃO JOSÉ DO DIVINO",
    "SÃO JOSÉ DO GOIABAL",
    "SÃO JOSÉ DO JACURI",
    "SÃO JOSÉ DO MANTIMENTO",
    "SÃO LOURENÇO",
    "SÃO MIGUEL DO ANTA",
    "SÃO PEDRO DA UNIÃO",
    "SÃO PEDRO DO SUAÇUÍ",
    "SÃO PEDRO DOS FERROS",
    "SÃO ROMÃO",
    "SÃO ROQUE DE MINAS",
    "SÃO SEBASTIÃO DA BELA VISTA",
    "SÃO SEBASTIÃO DA VARGEM ALEGRE",
    "SÃO SEBASTIÃO DO ANTA",
    "SÃO SEBASTIÃO DO MARANHÃO",
    "SÃO SEBASTIÃO DO OESTE",
    "SÃO SEBASTIÃO DO PARAÍSO",
    "SÃO SEBASTIÃO DO RIO PRETO",
    "SÃO SEBASTIÃO DO RIO VERDE",
    "SÃO THOMÉ DAS LETRAS",
    "SÃO TIAGO",
    "SÃO TOMÁS DE AQUINO",
    "SÃO VICENTE DE MINAS",
    "SAPUCAÍ-MIRIM",
    "SARDOÁ",
    "SARZEDO",
    "SEM-PEIXE",
    "SENADOR AMARAL",
    "SENADOR CORTES",
    "SENADOR FIRMINO",
    "SENADOR JOSÉ BENTO",
    "SENADOR MODESTINO GONÇALVES",
    "SENHORA DE OLIVEIRA",
    "SENHORA DO PORTO",
    "SENHORA DOS REMÉDIOS",
    "SERICITA",
    "SERITINGA",
    "SERRA AZUL DE MINAS",
    "SERRA DA SAUDADE",
    "SERRA DO SALITRE",
    "SERRA DOS AIMORÉS",
    "SERRANIA",
    "SERRANÓPOLIS DE MINAS",
    "SERRANOS",
    "SERRO",
    "SETE LAGOAS",
    "SETUBINHA",
    "SILVEIRÂNIA",
    "SILVIANÓPOLIS",
    "SIMÃO PEREIRA",
    "SIMONÉSIA",
    "SOBRÁLIA",
    "SOLEDADE DE MINAS",
    "TABULEIRO",
    "TAIOBEIRAS",
    "TAPARUBA",
    "TAPIRA",
    "TAPIRAÍ",
    "TAQUARAÇU DE MINAS",
    "TARUMIRIM",
    "TEIXEIRAS",
    "TEÓFILO OTONI",
    "TIMÓTEO",
    "TIRADENTES",
    "TIROS",
    "TOCANTINS",
    "TOCOS DO MOJI",
    "TOLEDO",
    "TOMBOS",
    "TRÊS CORAÇÕES",
    "TRÊS MARIAS",
    "TRÊS PONTAS",
    "TUMIRITINGA",
    "TUPACIGUARA",
    "TURMALINA",
    "TURVOLÂNDIA",
    "UBÁ",
    "UBAÍ",
    "UBAPORANGA",
    "UBERABA",
    "UBERLÂNDIA",
    "UMBURATIBA",
    "UNAÍ",
    "UNIÃO DE MINAS",
    "URUANA DE MINAS",
    "URUCÂNIA",
    "URUCUIA",
    "VARGEM ALEGRE",
    "VARGEM BONITA",
    "VARGEM GRANDE DO RIO PARDO",
    "VARGINHA",
    "VARJÃO DE MINAS",
    "VÁRZEA DA PALMA",
    "VARZELÂNDIA",
    "VAZANTE",
    "VERDELÂNDIA",
    "VEREDINHA",
    "VERÍSSIMO",
    "VERMELHO NOVO",
    "VESPASIANO",
    "VIÇOSA",
    "VIEIRAS",
    "VIRGEM DA LAPA",
    "VIRGÍNIA",
    "VIRGINÓPOLIS",
    "VIRGOLÂNDIA",
    "VISCONDE DO RIO BRANCO",
    "VOLTA GRANDE",
    "WENCESLAU BRAZ",
  ],
  GO: [
    "ABADIA DE GOIÁS",
    "ABADIÂNIA",
    "ACREÚNA",
    "ADELÂNDIA",
    "ÁGUA FRIA DE GOIÁS",
    "ÁGUA LIMPA",
    "ÁGUAS LINDAS DE GOIÁS",
    "ALEXÂNIA",
    "ALOÂNDIA",
    "ALTO HORIZONTE",
    "ALTO PARAÍSO DE GOIÁS",
    "ALVORADA DO NORTE",
    "AMARALINA",
    "AMERICANO DO BRASIL",
    "AMORINÓPOLIS",
    "ANÁPOLIS",
    "ANHANGUERA",
    "ANICUNS",
    "APARECIDA DE GOIÂNIA",
    "APARECIDA DO RIO DOCE",
    "APORÉ",
    "ARAÇU",
    "ARAGARÇAS",
    "ARAGOIÂNIA",
    "ARAGUAPAZ",
    "ARENÓPOLIS",
    "ARUANÃ",
    "AURILÂNDIA",
    "AVELINÓPOLIS",
    "BALIZA",
    "BARRO ALTO",
    "BELA VISTA DE GOIÁS",
    "BOM JARDIM DE GOIÁS",
    "BOM JESUS DE GOIÁS",
    "BONFINÓPOLIS",
    "BONÓPOLIS",
    "BRAZABRANTES",
    "BRITÂNIA",
    "BURITI ALEGRE",
    "BURITI DE GOIÁS",
    "BURITINÓPOLIS",
    "CABECEIRAS",
    "CACHOEIRA ALTA",
    "CACHOEIRA DE GOIÁS",
    "CACHOEIRA DOURADA",
    "CAÇU",
    "CAIAPÔNIA",
    "CALDAS NOVAS",
    "CALDAZINHA",
    "CAMPESTRE DE GOIÁS",
    "CAMPINAÇU",
    "CAMPINORTE",
    "CAMPO ALEGRE DE GOIÁS",
    "CAMPOS LIMPO DE GOIÁS",
    "CAMPOS BELOS",
    "CAMPOS VERDES",
    "CARMO DO RIO VERDE",
    "CASTELÂNDIA",
    "CATALÃO",
    "CATURAÍ",
    "CAVALCANTE",
    "CERES",
    "CEZARINA",
    "CHAPADÃO DO CÉU",
    "CIDADE OCIDENTAL",
    "COCALZINHO DE GOIÁS",
    "COLINAS DO SUL",
    "CÓRREGO DO OURO",
    "CORUMBÁ DE GOIÁS",
    "CORUMBAÍBA",
    "CRISTALINA",
    "CRISTIANÓPOLIS",
    "CRIXÁS",
    "CROMÍNIA",
    "CUMARI",
    "DAMIANÓPOLIS",
    "DAMOLÂNDIA",
    "DAVINÓPOLIS",
    "DIORAMA",
    "DIVINÓPOLIS DE GOIÁS",
    "DOVERLÂNDIA",
    "EDEALINA",
    "EDÉIA",
    "ESTRELA DO NORTE",
    "FAINA",
    "FAZENDA NOVA",
    "FIRMINÓPOLIS",
    "FLORES DE GOIÁS",
    "FORMOSA",
    "FORMOSO",
    "GAMELEIRA DE GOIÁS",
    "GOIANÁPOLIS",
    "GOIANDIRA",
    "GOIANÉSIA",
    "GOIÂNIA",
    "GOIANIRA",
    "GOIÁS",
    "GOIATUBA",
    "GOUVELÂNDIA",
    "GUAPÓ",
    "GUARAÍTA",
    "GUARANI DE GOIÁS",
    "GUARINOS",
    "HEITORAÍ",
    "HIDROLÂNDIA",
    "HIDROLINA",
    "IACIARA",
    "INACIOLÂNDIA",
    "INDIARA",
    "INHUMAS",
    "IPAMERI",
    "IPIRANGA DE GOIÁS",
    "IPORÁ",
    "ISRAELÂNDIA",
    "ITABERAÍ",
    "ITAGUARI",
    "ITAGUARU",
    "ITAJÁ",
    "ITAPACI",
    "ITAPIRAPUÃ",
    "ITAPURANGA",
    "ITARUMÃ",
    "ITAUÇU",
    "ITUMBIARA",
    "IVOLÂNDIA",
    "JANDAIA",
    "JARAGUÁ",
    "JATAÍ",
    "JAUPACI",
    "JESÚPOLIS",
    "JOVIÂNIA",
    "JUSSARA",
    "LAGOA SANTA",
    "LEOPOLDO DE BULHÕES",
    "LUZIÂNIA",
    "MAIRIPOTABA",
    "MAMBAÍ",
    "MARA ROSA",
    "MARZAGÃO",
    "MATRINCHÃ",
    "MAURILÂNDIA",
    "MIMOSO DE GOIÁS",
    "MINAÇU",
    "MINEIROS",
    "MOIPORÁ",
    "MONTE ALEGRE DE GOIÁS",
    "MONTES CLAROS DE GOIÁS",
    "MONTIVIDIU",
    "MONTIVIDIU DO NORTE",
    "MORRINHOS",
    "MORRO AGUDO DE GOIÁS",
    "MOSSÂMEDES",
    "MOZARLÂNDIA",
    "MUNDO NOVO",
    "MUTUNÓPOLIS",
    "NAZÁRIO",
    "NERÓPOLIS",
    "NIQUELÂNDIA",
    "NOVA AMÉRICA",
    "NOVA AURORA",
    "NOVA CRIXÁS",
    "NOVA GLÓRIA",
    "NOVA IGUAÇU DE GOIÁS",
    "NOVA ROMA",
    "NOVA VENEZA",
    "NOVO BRASIL",
    "NOVO GAMA",
    "NOVO PLANALTO",
    "ORIZONA",
    "OURO VERDE DE GOIÁS",
    "OUVIDOR",
    "PADRE BERNARDO",
    "PALESTINA DE GOIÁS",
    "PALMEIRAS DE GOIÁS",
    "PALMELO",
    "PALMINÓPOLIS",
    "PANAMÁ",
    "PARANAIGUARA",
    "PARAÚNA",
    "PEROLÂNDIA",
    "PETROLINA DE GOIÁS",
    "PILAR DE GOIÁS",
    "PIRACANJUBA",
    "PIRANHAS",
    "PIRENÓPOLIS",
    "PIRES DO RIO",
    "PLANALTINA",
    "PONTALINA",
    "PORANGATU",
    "PORTEIRÃO",
    "PORTELÂNDIA",
    "POSSE",
    "PROFESSOR JAMIL",
    "QUIRINÓPOLIS",
    "RIALMA",
    "RIANÁPOLIS",
    "RIO QUENTE",
    "RIO VERDE",
    "RUBIATABA",
    "SANCLERLÂNDIA",
    "SANTA BÁRBARA DE GOIÁS",
    "SANTA CRUZ DE GOIÁS",
    "SANTA FÉ DE GOIÁS",
    "SANTA HELENA DE GOIÁS",
    "SANTA ISABEL",
    "SANTA RITA DO ARAGUAIA",
    "SANTA RITA DO NOVO DESTINO",
    "SANTA ROSA DE GOIÁS",
    "SANTA TEREZA DE GOIÁS",
    "SANTA TEREZINHA DE GOIÁS",
    "SANTO ANTÔNIO DA BARRA",
    "SANTO ANTÔNIO DE GOIÁS",
    "SANTO ANTÔNIO DO DESCOBERTO",
    "SÃO DOMINGOS",
    "SÃO FRANCISCO DE GOIÁS",
    "SÃO JOÃO D'ALIANÇA",
    "SÃO JOÃO DA PARAÚNA",
    "SÃO LUÍS DE MONTES BELOS",
    "SÃO LUÍZ DO NORTE",
    "SÃO MIGUEL DO ARAGUAIA",
    "SÃO MIGUEL DO PASSA QUATRO",
    "SÃO PATRÍCIO",
    "SÃO SIMÃO",
    "SENADOR CANEDO",
    "SERRANÓPOLIS",
    "SILVÂNIA",
    "SIMOLÂNDIA",
    "SÍTIO D'ABADIA",
    "TAQUARAL DE GOIÁS",
    "TERESINA DE GOIÁS",
    "TEREZÓPOLIS DE GOIÁS",
    "TRÊS RANCHOS",
    "TRINDADE",
    "TROMBAS",
    "TURVÂNIA",
    "TURVELÂNDIA",
    "UIRAPURU",
    "URUAÇU",
    "URUANA",
    "URUTAÍ",
    "VALPARAÍSO DE GOIÁS",
    "VARJÃO",
    "VIANÓPOLIS",
    "VICENTINÓPOLIS",
    "VILA BOA",
    "VILA PROPÍCIO",
  ],
};
// const allCities = Object.values(stateCities);
// var cumulativeArr = [];
// Object.values(stateCities).map((arr) => {
//   cumulativeArr = cumulativeArr.concat(arr);
// });
// console.log(cumulativeArr.length);
function getLevenshteinDistance(string1, string2) {
  const matrix = Array(string1.length + 1)
    .fill(null)
    .map(() => Array(string2.length + 1).fill(null));

  for (let i = 0; i <= string1.length; i++) {
    matrix[i][0] = i;
  }

  for (let j = 0; j <= string2.length; j++) {
    matrix[0][j] = j;
  }

  for (let i = 1; i <= string1.length; i++) {
    for (let j = 1; j <= string2.length; j++) {
      const indicator = string1[i - 1] === string2[j - 1] ? 0 : 1;
      matrix[i][j] = Math.min(
        matrix[i - 1][j] + 1,
        matrix[i][j - 1] + 1,
        matrix[i - 1][j - 1] + indicator
      );
    }
  }

  return matrix[string1.length][string2.length];
}
function calculateStringSimilarity(string1, string2) {
  const maxLength = Math.max(string1.length, string2.length);
  const distance = getLevenshteinDistance(string1, string2);
  const similarity = (maxLength - distance) / maxLength;
  const similarityPercentage = similarity * 100;

  return similarityPercentage;
}
function getCity(leadCity) {
  var allCities = [];
  Object.values(stateCities).map((arr) => {
    allCities = allCities.concat(arr);
  });
  const matchingCity = allCities.find(
    (city) => calculateStringSimilarity(leadCity.toUpperCase(), city) > 80
  );
  return matchingCity;
}
function getUF(city, uf) {
  if (!city && !uf) return undefined;
  if (city && !uf) {
    var rightUF = undefined;
    Object.keys(stateCities).map((state) => {
      const foundOnCurrentState = stateCities[state].some(
        (x) => calculateStringSimilarity(city.toUpperCase(), x) > 60
      );
      if (foundOnCurrentState) rightUF = state;
    });
    return rightUF;
  }
  if (!city && uf) {
    console.log("PASSEI POR AQUI");
    const ufs = Object.keys(stateCities);
    const matchingUF = ufs.find((iUf) =>
      calculateStringSimilarity(uf.toUpperCase(), iUf)
    );
    return matchingUF;
  }
  if (city && uf) {
    const ufs = Object.keys(stateCities);
    const matchingUF = ufs.find((iUf) =>
      calculateStringSimilarity(uf.toUpperCase(), iUf)
    );
    return matchingUF;
  }
}
const city = getCity("ituiutaba");
const uf = getUF(undefined, undefined);
console.log(city, uf);
const leadObj = {
  id: "2967700569",
  email: "lucasfernandes@email.com",
  name: "NOVO TESTE ERP",
  company: null,
  job_title: null,
  bio: null,
  public_url:
    "http://app.rdstation.com.br/leads/public/79d87e7a-ecae-4945-96ec-91b42f42699f",
  created_at: "2023-07-11T16:39:06.166-03:00",
  opportunity: "false",
  number_conversions: "2",
  user: "amperemkt@gmail.com",
  first_conversion: {
    content: {
      event_type: "TASK_CREATED",
      event_identifier: "Tarefa criada no RD Station CRM",
      identificador: "Tarefa criada no RD Station CRM",
      event_timestamp: null,
      task_owner: "Matheus Oliveira",
      task_type: "call",
      created_at: "2023-07-11T19:39:09Z",
      due_date: "2023-07-12T07:39:00Z",
      task_title: "Tarefa criada no RD Station CRM",
      __cdp__original_event: {
        event_batch_uuid: "44e6816f-6d6d-45fe-a070-bf455f4b04a9",
        event_batch_index: 0,
        event_identifier: "Tarefa criada no RD Station CRM",
        event_uuid: "e680df2e-658e-4061-9f41-43660f11f1f2",
        event_type: "TASK_CREATED",
        event_family: "CDP",
        event_timestamp: null,
        payload: {
          task_owner: "Matheus Oliveira",
          task_type: "call",
          created_at: "2023-07-11T19:39:09Z",
          email: "lucasfernandes@email.com",
          due_date: "2023-07-12T07:39:00Z",
          name: "NOVO TESTE ERP",
          task_title: "Tarefa criada no RD Station CRM",
        },
      },
      email_lead: "lucasfernandes@email.com",
      Nome: "NOVO TESTE ERP",
      UF: null,
    },
    created_at: "2023-07-11T16:39:09.000-03:00",
    cumulative_sum: "1",
    source: "Tarefa criada no RD Station CRM",
    conversion_origin: {
      source: "unknown",
      medium: "unknown",
      value: null,
      campaign: "unknown",
      channel: "Unknown",
    },
  },
  last_conversion: {
    content: {
      event_type: "OPPORTUNITY_UPDATED",
      event_identifier: "Oportunidade atualizada no RD Station CRM",
      identificador: "Oportunidade atualizada no RD Station CRM",
      event_timestamp: null,
      funnel: "VENDAS",
      opportunity_title: "Oportunidade atualizada no RD Station CRM",
      owner: "amperemkt@gmail.com",
      opportunity_value: 0,
      mark_opportunity: false,
      funnel_stage: "Criação de Proposta",
      opportunity_url:
        "https://crm.rdstation.com/app/#/deals/64adafd6f7be470020761b33",
      updated_at: "2023-07-11T19:39:06Z",
      opportunity_origin: "Cliente Ativo",
      opportunity_score: 1,
      __cdp__original_event: {
        event_batch_uuid: "6337c357-5b63-4ef6-abde-586dac1cf5c8",
        event_batch_index: 0,
        event_identifier: "Oportunidade atualizada no RD Station CRM",
        event_uuid: "62aea966-be66-4e1c-ae10-e45d249c9ae0",
        event_type: "OPPORTUNITY_UPDATED",
        event_family: "CDP",
        event_timestamp: null,
        payload: {
          funnel: "VENDAS",
          name: "NOVO TESTE ERP",
          email: "lucasfernandes@email.com",
          opportunity_title: "Oportunidade atualizada no RD Station CRM",
          contact_owner_email: "amperemkt@gmail.com",
          opportunity_value: 0,
          mark_opportunity: false,
          funnel_stage: "Criação de Proposta",
          opportunity_url:
            "https://crm.rdstation.com/app/#/deals/64adafd6f7be470020761b33",
          updated_at: "2023-07-11T19:39:06Z",
          opportunity_origin: "Cliente Ativo",
          opportunity_score: 1,
        },
      },
      email_lead: "lucasfernandes@email.com",
      Nome: "NOVO TESTE ERP",
      UF: null,
    },
    created_at: "2023-07-11T16:39:10.684-03:00",
    cumulative_sum: "2",
    source: "Oportunidade atualizada no RD Station CRM",
    conversion_origin: {
      source: "unknown",
      medium: "unknown",
      value: null,
      campaign: "unknown",
      channel: "Unknown",
    },
  },
  custom_fields: {
    "Origem da Oportunidade no CRM (última atualização)": "Cliente Ativo",
    "Qualificação da Oportunidade no CRM (última atualização)": "1",
    "Etapa do funil de vendas no CRM (última atualização)":
      "Criação de Proposta",
    "Valor total da Oportunidade no CRM (última atualização)": "0.0",
    "Nome do responsável pela Oportunidade no CRM (última atualização)":
      "Matheus Oliveira",
    "Funil de vendas no CRM (última atualização)": "VENDAS",
  },
  website: null,
  personal_phone: "3499312321",
  mobile_phone: null,
  city: null,
  state: null,
  tags: [],
  lead_stage: "Lead",
  last_marked_opportunity_date: null,
  uuid: "79d87e7a-ecae-4945-96ec-91b42f42699f",
  fit_score: "d",
  interest: 0,
};
console.log(
  leadObj.last_conversion?.content?.opportunity_url.split("deals/")[1]
);
